# Generated by Django 4.2.7 on 2023-12-13 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0008_alter_sample_negative_film_count'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoot_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('date_settled', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('deposit', models.FloatField()),
                ('pay_status', models.IntegerField(choices=[(0, '未付款'), (1, '已付定金'), (2, '已付全款')], default=0)),
                ('location', models.CharField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='customers.customer')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='samples.sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
