# Generated by Django 4.2.7 on 2023-12-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shoot_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
