# Generated by Django 4.2.7 on 2023-12-17 22:57

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_end_time_alter_schedule_shoot_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
