# Generated by Django 4.2.7 on 2023-12-18 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0003_schedule_created_at_schedule_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='executors',
            field=models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
