# Generated by Django 4.2.7 on 2023-12-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_historicalschedule_changed_by_schedule_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='HistoricalSchedule',
        ),
    ]
