# Generated by Django 4.2.7 on 2023-12-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_alter_historicalschedule_changed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalschedule',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='changed_by',
        ),
    ]
