# Generated by Django 4.2.7 on 2023-12-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_alter_historicalschedule_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='pay_status',
            field=models.IntegerField(choices=[(-1, '已关闭'), (0, '未付款'), (1, '已付定金'), (2, '已付全款'), (3, '完成拍摄'), (4, '订单完成')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pay_status',
            field=models.IntegerField(choices=[(-1, '已关闭'), (0, '未付款'), (1, '已付定金'), (2, '已付全款'), (3, '完成拍摄'), (4, '订单完成')], default=0),
        ),
    ]
