# Generated by Django 4.2.7 on 2023-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_alter_historicalschedule_pay_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='_change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='_change_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
