# Generated by Django 4.2.7 on 2023-12-22 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_rename_prive_visible_sample_price_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_customer_avatar_customer_desc'),
        ('schedules', '0013_historicalschedule__change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to='samples.sample'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
