# Generated by Django 4.2.7 on 2023-12-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_mobile_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
