# Generated by Django 4.2.7 on 2023-11-27 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=500)),
                ('covers', models.TextField(max_length=1000000)),
                ('details', models.TextField(max_length=1000000)),
                ('price', models.FloatField()),
                ('prive_visible', models.BooleanField(default=True)),
                ('deposit', models.FloatField()),
                ('deposit_visible', models.BooleanField(default=True)),
                ('basic_info_visible', models.BooleanField(default=True)),
                ('costume_offer', models.BooleanField(default=False)),
                ('costume_count', models.IntegerField()),
                ('negative_film_count', models.IntegerField()),
                ('nega_film_all_offer', models.BooleanField(default=True)),
                ('shooting_time', models.IntegerField()),
                ('refine_count', models.IntegerField()),
                ('shooting_indoor', models.BooleanField(default=True)),
                ('shooting_scene_indoor_count', models.IntegerField()),
                ('custom_detail', models.TextField()),
                ('public', models.BooleanField(default=True)),
                ('tips', models.TextField()),
                ('tags', models.ManyToManyField(to='samples.samplelabel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
