# Generated by Django 4.2.7 on 2023-11-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='sample',
            name='costume_count',
            field=models.IntegerField(default=0),
        ),
    ]
