# Generated by Django 4.2.7 on 2023-11-28 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0002_rename_user_id_sample_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique name for each person'),
        ),
    ]
