# Generated by Django 4.2.7 on 2023-11-29 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0003_alter_sample_user_sample_unique_name_for_each_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('basic_info_visible', models.BooleanField(default=True)),
                ('costume_offer', models.BooleanField(default=False)),
                ('costume_count', models.IntegerField(default=0)),
                ('negative_film_count', models.IntegerField()),
                ('nega_film_all_offer', models.BooleanField(default=True)),
                ('shooting_time', models.IntegerField()),
                ('refine_count', models.IntegerField()),
                ('shooting_indoor', models.BooleanField(default=True)),
                ('shooting_scene_indoor_count', models.IntegerField()),
                ('custom_detail', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sampletemplate',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique template name for each person'),
        ),
    ]
