# Generated by Django 4.2.7 on 2023-11-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_remove_sampletemplate_custom_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='custom_costume_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='custom_shooting_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampletemplate',
            name='custom_costume_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sampletemplate',
            name='custom_shooting_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='costume_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sample',
            name='refine_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='shooting_scene_indoor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='shooting_time',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='costume_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='negative_film_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='shooting_time',
            field=models.IntegerField(default=None),
        ),
    ]
