# Generated by Django 4.2.7 on 2023-12-04 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_sample_custom_costume_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 4, 7, 25, 37, 773591, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
