# Generated by Django 4.2.7 on 2023-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_sample_created_at_sample_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='negative_film_count',
            field=models.IntegerField(default=0),
        ),
    ]
