# Generated by Django 4.2.7 on 2023-12-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_alter_sample_negative_film_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='custom_costume_count',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='custom_shooting_time',
        ),
        migrations.RemoveField(
            model_name='sampletemplate',
            name='custom_costume_count',
        ),
        migrations.RemoveField(
            model_name='sampletemplate',
            name='custom_shooting_time',
        ),
        migrations.AlterField(
            model_name='sample',
            name='basic_info_visible',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='costume_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='costume_offer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='deposit_visible',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='nega_film_all_offer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='negative_film_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='prive_visible',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='public',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='refine_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='shooting_indoor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='shooting_scene_indoor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='shooting_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='basic_info_visible',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='costume_offer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='nega_film_all_offer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='refine_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='shooting_indoor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='shooting_scene_indoor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampletemplate',
            name='shooting_time',
            field=models.IntegerField(),
        ),
    ]
