# Generated by Django 4.2.7 on 2023-12-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_remove_sample_custom_costume_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='prive_visible',
            new_name='price_visible',
        ),
    ]
