# Generated by Django 4.2.7 on 2023-12-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_alter_sample_shooting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplelabel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='samples.samplelabel'),
        ),
    ]
