# Generated by Django 4.2.7 on 2023-12-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_samplelabel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
