# Generated by Django 4.2.7 on 2023-12-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_nickname_alter_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
