# Generated by Django 4.2.7 on 2023-12-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='covers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
