# Generated by Django 4.2.7 on 2023-12-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_picturefolder_name_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='picturefolder',
            name='name unique',
        ),
    ]
