# Generated by Django 4.2.7 on 2023-12-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_picturefolder_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefolder',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pictures.picturefolder'),
        ),
    ]
