# Generated by Django 4.2.7 on 2023-12-05 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0008_pictureinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureinfo',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pictureinfo',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pictureinfo',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folderuuid',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='picturefolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name', 'user'), name='32432432'),
        ),
        migrations.AddConstraint(
            model_name='pictureinfo',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'folder'), name='12323131'),
        ),
    ]
