# Generated by Django 4.2.7 on 2023-12-06 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_pictureinfo_height_pictureinfo_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureinfo',
            name='uuid_name',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
