# Generated by Django 4.2.7 on 2023-12-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_pictureinfo_uuid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureinfo',
            name='ext',
            field=models.CharField(default=''),
        ),
    ]
