# Generated by Django 4.2.7 on 2023-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0011_pictureinfo_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureinfo',
            name='ext',
            field=models.CharField(blank=True, default=''),
        ),
    ]
