# Generated by Django 4.2.7 on 2023-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_alter_sample_negative_film_count'),
        ('pictures', '0013_alter_pictureinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureinfo',
            name='labels',
            field=models.ManyToManyField(blank=True, default=[], null=True, to='samples.samplelabel'),
        ),
    ]
