# Generated by Django 4.2.7 on 2023-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0015_alter_pictureinfo_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureinfo',
            name='file',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
