# Generated by Django 4.2.7 on 2023-12-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0016_pictureinfo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureinfo',
            name='file',
        ),
    ]
