# Generated by Django 4.2.7 on 2023-12-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0017_remove_pictureinfo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
